//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetDotnet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PDResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PDResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanetDotnet.Resources.PDResources", typeof(PDResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already an author?.
        /// </summary>
        public static string ALREADY_AUTHOR {
            get {
                return ResourceManager.GetString("ALREADY_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can show off to the world by incorporating this badge into your blog. If you would have it link back to us, that would be totally awesome!.
        /// </summary>
        public static string ALREADY_AUTHOR_BODY {
            get {
                return ResourceManager.GetString("ALREADY_AUTHOR_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! Good to have you aboard!.
        /// </summary>
        public static string ALREADY_AUTHOR_SUBTITLE {
            get {
                return ResourceManager.GetString("ALREADY_AUTHOR_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet .NET.
        /// </summary>
        public static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string AUTHORS {
            get {
                return ResourceManager.GetString("AUTHORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is random. Refresh to shuffle..
        /// </summary>
        public static string AUTHORS_ALERT {
            get {
                return ResourceManager.GetString("AUTHORS_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors&apos; opinions.
        /// </summary>
        public static string AUTHORS_OPINION {
            get {
                return ResourceManager.GetString("AUTHORS_OPINION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We pride ourselves on diversity of thought - our strength is in our unique collective viewpoints experiences.
        /// </summary>
        public static string AUTHORS_OPINION_1 {
            get {
                return ResourceManager.GetString("AUTHORS_OPINION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We love sharing this diversity with the community, and we don&apos;t censor or curate these blogs - they represent the authors&apos; opinions..
        /// </summary>
        public static string AUTHORS_OPINION_2 {
            get {
                return ResourceManager.GetString("AUTHORS_OPINION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide a &lt;a href=&quot;{0}&quot;&gt;way to opt-in what content gets syndicated&lt;/a&gt; and encourage authors to use it..
        /// </summary>
        public static string AUTHORS_OPINION_3 {
            get {
                return ResourceManager.GetString("AUTHORS_OPINION_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I just read it here?.
        /// </summary>
        public static string CAN_I_READ_HERE {
            get {
                return ResourceManager.GetString("CAN_I_READ_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can, but we don&apos;t want to redirect traffic from our people&apos;s individual sites. Here&apos;s a &lt;a href=&quot;{0}&quot;&gt;sneak peek&lt;/a&gt; in case you&apos;re still trying to decide to subscribe..
        /// </summary>
        public static string CAN_I_READ_HERE_BODY {
            get {
                return ResourceManager.GetString("CAN_I_READ_HERE_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string FACEBOOK {
            get {
                return ResourceManager.GetString("FACEBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you blog about .NET? Add yourself to the aggregator by sending in a &lt;a href=&quot;https://github.com/mabroukmahdhi/planetdotnet&quot;&gt;pull-request to our repository&lt;/a&gt; on GitHub. Planet .NET is not affiliated with Microsoft and is a open-source project maintained by the community for the community..
        /// </summary>
        public static string FOOTER_TEXT {
            get {
                return ResourceManager.GetString("FOOTER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on author name and tag....
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string TWITTER {
            get {
                return ResourceManager.GetString("TWITTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are an aggregator of content from .NET Community members. Why subscribe individually when you can subscribe to one convenient RSS feed, to see all the content generated by the community members in you news reader. If RSS isn&apos;t your thing, follow our &lt;a href=&quot;{0}&quot;&gt;Twitter&lt;/a&gt; or &lt;a href=&quot;{1}&quot;&gt;Facebook&lt;/a&gt; accounts which are automatically updated with the latest content from the community..
        /// </summary>
        public static string WELCOME_INTRO {
            get {
                return ResourceManager.GetString("WELCOME_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, and welcome to Planet .NET!.
        /// </summary>
        public static string WELCOME_SUBTITLE {
            get {
                return ResourceManager.GetString("WELCOME_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WELCOME_TITLE {
            get {
                return ResourceManager.GetString("WELCOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where&apos;s the feed?!.
        /// </summary>
        public static string WHERE_IS_FEED {
            get {
                return ResourceManager.GetString("WHERE_IS_FEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point your RSS reader at this page and it&apos;ll find it; or subscribe to &lt;a href=&quot;{0}&quot;&gt;the feed manually&lt;/a&gt;..
        /// </summary>
        public static string WHERE_IS_FEED_BODY {
            get {
                return ResourceManager.GetString("WHERE_IS_FEED_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you all?.
        /// </summary>
        public static string WHO_ARE_YOU {
            get {
                return ResourceManager.GetString("WHO_ARE_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are community members! &lt;br /&gt;You can read more &lt;a href=&quot;{0}&quot;&gt;about us here&lt;/a&gt;..
        /// </summary>
        public static string WHO_ARE_YOU_BODY {
            get {
                return ResourceManager.GetString("WHO_ARE_YOU_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many thanks to the &lt;a href=&quot;https://www.planetxamarin.com/&quot;&gt;Planet Xamarin&lt;/a&gt; for this awesome template!.
        /// </summary>
        public static string XAMARIN_PLANET_THANKS {
            get {
                return ResourceManager.GetString("XAMARIN_PLANET_THANKS", resourceCulture);
            }
        }
    }
}
