//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetDotnet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PDResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PDResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanetDotnet.Resources.PDResources", typeof(PDResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet .NET.
        /// </summary>
        public static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string AUTHORS {
            get {
                return ResourceManager.GetString("AUTHORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is random. Refresh to shuffle..
        /// </summary>
        public static string AUTHORS_ALERT {
            get {
                return ResourceManager.GetString("AUTHORS_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string FACEBOOK {
            get {
                return ResourceManager.GetString("FACEBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you blog about .NET? Add yourself to the aggregator by sending in a &lt;a href=&quot;https://github.com/mabroukmahdhi/planetdotnet&quot;&gt;pull-request to our repository&lt;/a&gt; on GitHub. Planet .NET is not affiliated with Microsoft and is a open-source project maintained by the community for the community..
        /// </summary>
        public static string FOOTER_TEXT {
            get {
                return ResourceManager.GetString("FOOTER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on author name and tag....
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string TWITTER {
            get {
                return ResourceManager.GetString("TWITTER", resourceCulture);
            }
        }
    }
}
